# Generated by Django 4.0.1 on 2022-02-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_cont',
            new_name='cont',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
