# Generated by Django 5.0.6 on 2024-06-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_contactmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessages',
            options={'verbose_name_plural': 'Contact Messages'},
        ),
    ]
